<?php
include 'koneksi.php';
$data = [
    [
        "nik" => "1106505905237850",
        "nama" => "ARCELA ZULFA SHAKAYLA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "5/19/23",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "ERIKA DIO SANDA",
        "alamat" => "BUR BIAH",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "0 th, 5 bln, 13 h",
        "tgl_pengukuran" => "11/1/23",
        "berat" => "6.9",
        "tinggi" => "64",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106505309211220",
        "nama" => "AISYAH IHZA TAHIRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "9/13/21",
        "bb_lahir" => "3.2",
        "tb_lahir" => "48",
        "nama_ortu" => "SASTRI RAHMANA",
        "alamat" => "ATU TULU",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 1 bln, 29 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "11",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104114710199990",
        "nama" => "ALFA AQILA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "8/7/19",
        "bb_lahir" => "2.9",
        "tb_lahir" => "46",
        "nama_ortu" => "ANISA RAMADNI",
        "alamat" => "BAHGIE",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 5 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "13.2",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1171096469899990",
        "nama" => "ARVINO MAUZA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "12/12/18",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "HUDAINI",
        "alamat" => "BEBESEN",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "0 th, 5 bln, 13 h",
        "tgl_pengukuran" => "11/1/23",
        "berat" => "6.9",
        "tinggi" => "64",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "110405520699999",
        "nama" => "AZHARI RAHMAT",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "10/10/28",
        "bb_lahir" => "3.2",
        "tb_lahir" => "48",
        "nama_ortu" => "MUSFIRA",
        "alamat" => "BLANG GELE",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 1 bln, 29 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "11",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104031208799990",
        "nama" => "CUT FAZINDA KANZIA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "11/18/18",
        "bb_lahir" => "2.9",
        "tb_lahir" => "46",
        "nama_ortu" => "FAUZI HADIAN",
        "alamat" => "BLANG KOLAK I",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 5 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "13.2",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030305190000",
        "nama" => "HABIB RIZKI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "5/3/19",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "YASMIATI",
        "alamat" => "BLANG KOLAK I",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "0 th, 5 bln, 13 h",
        "tgl_pengukuran" => "11/1/23",
        "berat" => "6.9",
        "tinggi" => "64",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "11040368011900000",
        "nama" => "KAYLA CHAYANI",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "1/28/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "48",
        "nama_ortu" => "AHMAD ZAILANI",
        "alamat" => "BLANG KOLAK II",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 1 bln, 29 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "11",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030200920000",
        "nama" => "KENZO RAHMAN",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "9/20/20",
        "bb_lahir" => "2.9",
        "tb_lahir" => "46",
        "nama_ortu" => "IMAM AHMADI",
        "alamat" => "BUR BIAH",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 5 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "13.2",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1103072110180000",
        "nama" => "M. ARIFIN",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "10/21/18",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "MANSUR",
        "alamat" => "DALING",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "0 th, 5 bln, 13 h",
        "tgl_pengukuran" => "11/1/23",
        "berat" => "6.9",
        "tinggi" => "64",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106500111197110",
        "nama" => "M. BILAL ALFATIH",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "11/1/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "48",
        "nama_ortu" => "FADIAN",
        "alamat" => "EMPUS TALU",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 1 bln, 29 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "11",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104037107040000",
        "nama" => "MUHAMMAD ALFATIH",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "8/11/22",
        "bb_lahir" => "2.9",
        "tb_lahir" => "46",
        "nama_ortu" => "AFIKAH SYAHIRA",
        "alamat" => "GELE LAH",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 5 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "13.2",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1103031107899990",
        "nama" => "NURHALIZA PUTRI",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "8/13/19",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "IMRAN",
        "alamat" => "KEBET",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "0 th, 5 bln, 13 h",
        "tgl_pengukuran" => "11/1/23",
        "berat" => "6.9",
        "tinggi" => "64",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104031004200000",
        "nama" => "RAIHAN ALGIFAHRI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "4/10/20",
        "bb_lahir" => "3.2",
        "tb_lahir" => "48",
        "nama_ortu" => "SAMUYADI",
        "alamat" => "KEMILI",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 1 bln, 29 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "11",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104031511018000",
        "nama" => "RASYA YUDA A.",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "10/15/18",
        "bb_lahir" => "2.9",
        "tb_lahir" => "46",
        "nama_ortu" => "SRIE YANDA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 5 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "13.2",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104036006230000",
        "nama" => "RAYYA ALMAHYRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "6/20/23",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "LAILAWATI",
        "alamat" => "LELABU",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "0 th, 5 bln, 13 h",
        "tgl_pengukuran" => "11/1/23",
        "berat" => "6.9",
        "tinggi" => "64",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104033006230000",
        "nama" => "RIZQY ARSYAKA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "6/30/23",
        "bb_lahir" => "3.2",
        "tb_lahir" => "48",
        "nama_ortu" => "JULIANTI",
        "alamat" => "LEMAH BURBANA",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 1 bln, 29 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "11",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "11040315077999900",
        "nama" => "SYAHLA MUDE JAMARA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "11/13/18",
        "bb_lahir" => "2.9",
        "tb_lahir" => "46",
        "nama_ortu" => "JAMALUDDIN",
        "alamat" => "MAH BENGI",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 5 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "13.2",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030610180000",
        "nama" => "TEUKU YAZID AL FAQI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "10/6/18",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "MULIYA YANTI",
        "alamat" => "MONGAL",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "0 th, 5 bln, 13 h",
        "tgl_pengukuran" => "11/1/23",
        "berat" => "6.9",
        "tinggi" => "64",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "11040315077999900",
        "nama" => "SYAHLA MUDE JAMARA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "11/13/18",
        "bb_lahir" => "3.2",
        "tb_lahir" => "48",
        "nama_ortu" => "JAMALUDDIN",
        "alamat" => "NUNANG ANTARA",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 1 bln, 29 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "11",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106504202232990",
        "nama" => "ALIFA ZEA AMANDA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "2/2/23",
        "bb_lahir" => "2.9",
        "tb_lahir" => "46",
        "nama_ortu" => "MURNI RAYATI ZIKRULLAH",
        "alamat" => "PENDERE SARIL",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 5 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "13.2",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104084712180000",
        "nama" => "ALISA AMIRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "12/7/18",
        "bb_lahir" => "3.2",
        "tb_lahir" => "48",
        "nama_ortu" => "JAMALUDDIN",
        "alamat" => "KEBET",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 1 bln, 29 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "11",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106505706219980",
        "nama" => "ALISA ZAHRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "6/17/21",
        "bb_lahir" => "3.2",
        "tb_lahir" => "50",
        "nama_ortu" => "MULIYA YANTI",
        "alamat" => "MAH BENGI",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 6 bln, 21 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "10",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104036909190000",
        "nama" => "ALLA ZAHIRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "9/29/19",
        "bb_lahir" => "2.9",
        "tb_lahir" => "40",
        "nama_ortu" => "YANDA",
        "alamat" => "MONGAL",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 0 bln, 22 h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "9.4",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106502606216700",
        "nama" => "ALZAIDAN",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "6/26/21",
        "bb_lahir" => "2.8",
        "tb_lahir" => "49",
        "nama_ortu" => "MUYADI",
        "alamat" => "TENSAREN",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 7 bln, 15 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "11",
        "tinggi" => "90",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106503006218110",
        "nama" => "AMAR ALFARIZI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "6/30/21",
        "bb_lahir" => "3",
        "tb_lahir" => "48",
        "nama_ortu" => "HAJIRWAN",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 24 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "15.5",
        "tinggi" => "112",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104176904190000",
        "nama" => "AMARA QAILA MEDINA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "4/29/19",
        "bb_lahir" => "3",
        "tb_lahir" => "50",
        "nama_ortu" => "IKA ARMALA",
        "alamat" => "SIMPANG EMPAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 7 bln, 11 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "13",
        "tinggi" => "103",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106506702212220",
        "nama" => "AMIRA SYAKILA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "2/27/21",
        "bb_lahir" => "3.2",
        "tb_lahir" => "49",
        "nama_ortu" => "BASRAH",
        "alamat" => "UMANG",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 0 bln, 13 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "13.3",
        "tinggi" => "101",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1207261201190000",
        "nama" => "ANAN DHIAURRAHMAN",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "1/12/19",
        "bb_lahir" => "1.8",
        "tb_lahir" => "45",
        "nama_ortu" => "YANTI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 4 bln, 20 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "6.1",
        "tinggi" => "69",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106504406238240",
        "nama" => "ANGELINE ALLEA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "6/4/23",
        "bb_lahir" => "3.2",
        "tb_lahir" => "45",
        "nama_ortu" => "HAMDANI",
        "alamat" => "TAN SARIL",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 5 bln, 14 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "15.9",
        "tinggi" => "115",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106504307219060",
        "nama" => "ANINDIRA AZAHRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "7/3/21",
        "bb_lahir" => "3.1",
        "tb_lahir" => "50",
        "nama_ortu" => "YUDI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 2 bln, 2 h",
        "tgl_pengukuran" => "8/14/23",
        "berat" => "16",
        "tinggi" => "120",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104034504230000",
        "nama" => "ANNASYA SAILA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "4/5/23",
        "bb_lahir" => "3.3",
        "tb_lahir" => "51",
        "nama_ortu" => "JUSILA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 1 bln, 14",
        "tgl_pengukuran" => "3/2/22",
        "berat" => "12.4",
        "tinggi" => "101",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104036401190000",
        "nama" => "ARCYILA PUTRI",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "1/24/19",
        "bb_lahir" => "2.2",
        "tb_lahir" => "49",
        "nama_ortu" => "ZURAIDAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 2 bln, 20 h",
        "tgl_pengukuran" => "11/10/23",
        "berat" => "13.2",
        "tinggi" => "119",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104171705230000",
        "nama" => "ARDALAN MIZAMAUL",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "5/17/23",
        "bb_lahir" => "3.4",
        "tb_lahir" => "52",
        "nama_ortu" => "SUPARNI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 1 bln, 30 h",
        "tgl_pengukuran" => "11/9/23",
        "berat" => "14.5",
        "tinggi" => "125",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106502205216610",
        "nama" => "ARJET ALFARISKI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "5/22/21",
        "bb_lahir" => "2.9",
        "tb_lahir" => "51",
        "nama_ortu" => "SALAWATI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 8 bln, 20, h",
        "tgl_pengukuran" => "10/11/23",
        "berat" => "14.2",
        "tinggi" => "110",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030506200000",
        "nama" => "ARSYA ALIQ SYAHPUTRA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "6/5/20",
        "bb_lahir" => "3.5",
        "tb_lahir" => "52",
        "nama_ortu" => "KARMINA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 4 bln, 20h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "15.2",
        "tinggi" => "133",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104032005199990",
        "nama" => "ASYRAFUL MUBARAQ",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "5/20/19",
        "bb_lahir" => "3",
        "tb_lahir" => "50",
        "nama_ortu" => "RAMLI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 1 bln, 28 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "6.3",
        "tinggi" => "70",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104034211190000",
        "nama" => "ATIKA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "3/2/19",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "YANTI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 1 bln, 13 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "9.3",
        "tinggi" => "111",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104034308220000",
        "nama" => "AULIA PUTRI",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "8/3/22",
        "bb_lahir" => "2.9",
        "tb_lahir" => "48",
        "nama_ortu" => "ZURAIDAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 4 bln, 29 h",
        "tgl_pengukuran" => "8/12/23",
        "berat" => "15.4",
        "tinggi" => "123",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104037003930000",
        "nama" => "AURA ATTAQIN",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "9/20/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "49",
        "nama_ortu" => "HARISDAWATI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 2 bln, 29 h",
        "tgl_pengukuran" => "8/12/23",
        "berat" => "14.1",
        "tinggi" => "110",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104175306220000",
        "nama" => "AUREL QUEENSYA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "6/13/22",
        "bb_lahir" => "3.1",
        "tb_lahir" => "52",
        "nama_ortu" => "HINDAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 5 bln, 23h",
        "tgl_pengukuran" => "7/12/23",
        "berat" => "16.2",
        "tinggi" => "143",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "120303410799999",
        "nama" => "AYYUP ALFARISKI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "9/15/20",
        "bb_lahir" => "2.9",
        "tb_lahir" => "52",
        "nama_ortu" => "SITI AISAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 6 bln, 4 h",
        "tgl_pengukuran" => "6/12/23",
        "berat" => "14.2",
        "tinggi" => "123",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104036812180000",
        "nama" => "AZZALEA KHALIKA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "12/28/18",
        "bb_lahir" => "3.1",
        "tb_lahir" => "51",
        "nama_ortu" => "KASMAWATI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 7 bln, 7 h",
        "tgl_pengukuran" => "5/13/23",
        "berat" => "13.2",
        "tinggi" => "132",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104031704190000",
        "nama" => "AZZAM FAHREZA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "4/17/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "49",
        "nama_ortu" => "NURJANAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 6 bln, 4 h",
        "tgl_pengukuran" => "6/12/23",
        "berat" => "14.2",
        "tinggi" => "123",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106501404218770",
        "nama" => "BAGAS SYAHPUTRA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "4/14/21",
        "bb_lahir" => "2.8",
        "tb_lahir" => "48",
        "nama_ortu" => "MURNI RAYATI ZIKRULLAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 6 bln, 16 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "12.2",
        "tinggi" => "102",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104035807190000",
        "nama" => "CUT JASRA UMAIZA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "7/18/19",
        "bb_lahir" => "2.8",
        "tb_lahir" => "49",
        "nama_ortu" => "JUSILA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 6 bln, 4 h",
        "tgl_pengukuran" => "3 th, 6 bln, 4 h",
        "berat" => "14.2",
        "tinggi" => "123",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104034603190000",
        "nama" => "DAMLA HAMIDA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "3/6/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "50",
        "nama_ortu" => "ZURAIDAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 6 bln, 21 h",
        "tgl_pengukuran" => "3 th, 6 bln, 4 h",
        "berat" => "10",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106507012192440",
        "nama" => "DEVI AZZAHRA PUTRI",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "12/30/19",
        "bb_lahir" => "2.9",
        "tb_lahir" => "40",
        "nama_ortu" => "SITI AISAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 0 bln, 22 h",
        "tgl_pengukuran" => "3 th, 6 bln, 4 h",
        "berat" => "9.4",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104031808200000",
        "nama" => "DHEEFIN UZEIR",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "8/18/20",
        "bb_lahir" => "2.8",
        "tb_lahir" => "49",
        "nama_ortu" => "KASMAWATI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 7 bln, 15 h",
        "tgl_pengukuran" => "3 th, 6 bln, 4 h",
        "berat" => "11",
        "tinggi" => "90",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106505507218000",
        "nama" => "EDELWIS MOTAVANI",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "7/15/21",
        "bb_lahir" => "3",
        "tb_lahir" => "48",
        "nama_ortu" => "HAJIRWAN",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 24 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "15.5",
        "tinggi" => "112",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "110403100219001",
        "nama" => "EDZARD EL HISYAM",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "2/14/19",
        "bb_lahir" => "3",
        "tb_lahir" => "50",
        "nama_ortu" => "IKA ARMALA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 7 bln, 11 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "13",
        "tinggi" => "103",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104031108190000",
        "nama" => "EL GHIFFAR ADHIA ARIVI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "8/11/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "49",
        "nama_ortu" => "BASRAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 0 bln, 13 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "13.3",
        "tinggi" => "101",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104033112180000",
        "nama" => "FAHRI AKBAR FASARIBU",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "12/31/18",
        "bb_lahir" => "1.8",
        "tb_lahir" => "45",
        "nama_ortu" => "YANTI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 4 bln, 20 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "6.1",
        "tinggi" => "69",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106504911218210",
        "nama" => "FAIDA QABRINA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "11/9/21",
        "bb_lahir" => "3.2",
        "tb_lahir" => "45",
        "nama_ortu" => "HAMDANI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 5 bln, 14 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "15.9",
        "tinggi" => "115",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104036711180000",
        "nama" => "FAIHA AZZHRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "11/27/18",
        "bb_lahir" => "3.1",
        "tb_lahir" => "50",
        "nama_ortu" => "YUDI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 2 bln, 2 h",
        "tgl_pengukuran" => "8/14/23",
        "berat" => "16",
        "tinggi" => "120",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030406999990",
        "nama" => "FAIZ AL AZAMI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "7/29/19",
        "bb_lahir" => "3.3",
        "tb_lahir" => "51",
        "nama_ortu" => "JUSILA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 1 bln, 14",
        "tgl_pengukuran" => "3/2/22",
        "berat" => "12.4",
        "tinggi" => "101",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104032204190000",
        "nama" => "FAZREL ALVA RIZKY",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "4/22/19",
        "bb_lahir" => "2.2",
        "tb_lahir" => "49",
        "nama_ortu" => "ZURAIDAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 2 bln, 20 h",
        "tgl_pengukuran" => "11/10/23",
        "berat" => "13.2",
        "tinggi" => "119",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104035905799990",
        "nama" => "GHIFAR AL MUHARRMA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "8/25/20",
        "bb_lahir" => "3.4",
        "tb_lahir" => "52",
        "nama_ortu" => "SUPARNI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 1 bln, 30 h",
        "tgl_pengukuran" => "11/9/23",
        "berat" => "14.5",
        "tinggi" => "125",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104032711190000",
        "nama" => "GHIFARI ABBASY",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "11/27/19",
        "bb_lahir" => "2.9",
        "tb_lahir" => "51",
        "nama_ortu" => "SALAWATI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 8 bln, 20, h",
        "tgl_pengukuran" => "10/11/23",
        "berat" => "14.2",
        "tinggi" => "110",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1010403271222000",
        "nama" => "GIFARI ATHARAZKA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "12/2/22",
        "bb_lahir" => "3.5",
        "tb_lahir" => "52",
        "nama_ortu" => "KARMINA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 4 bln, 20h",
        "tgl_pengukuran" => "10/12/23",
        "berat" => "15.2",
        "tinggi" => "133",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1271185502200000",
        "nama" => "HAFIDZA LUTHFIA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "2/15/20",
        "bb_lahir" => "3",
        "tb_lahir" => "50",
        "nama_ortu" => "RAMLI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 1 bln, 28 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "6.3",
        "tinggi" => "70",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104036908190000",
        "nama" => "HANIN RAUDATUN NAIN",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "8/29/19",
        "bb_lahir" => "3.1",
        "tb_lahir" => "49",
        "nama_ortu" => "YANTI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 1 bln, 13 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "9.3",
        "tinggi" => "111",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "111703050799999",
        "nama" => "HARSA GIUANO",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "7/20/20",
        "bb_lahir" => "2.9",
        "tb_lahir" => "48",
        "nama_ortu" => "ZURAIDAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 4 bln, 29 h",
        "tgl_pengukuran" => "8/12/23",
        "berat" => "15.4",
        "tinggi" => "123",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106504806211350",
        "nama" => "JUNAIRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "6/8/21",
        "bb_lahir" => "3.2",
        "tb_lahir" => "49",
        "nama_ortu" => "HARISDAWATI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 2 bln, 29 h",
        "tgl_pengukuran" => "8/12/23",
        "berat" => "14.1",
        "tinggi" => "110",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1171040901899990",
        "nama" => "KENZI AROYAN ALFARISKI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "7/22/20",
        "bb_lahir" => "3.1",
        "tb_lahir" => "52",
        "nama_ortu" => "HINDAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 5 bln, 23h",
        "tgl_pengukuran" => "7/12/23",
        "berat" => "16.2",
        "tinggi" => "143",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030911180000",
        "nama" => "KENZI HARDANA PUTRA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "11/9/18",
        "bb_lahir" => "2.9",
        "tb_lahir" => "52",
        "nama_ortu" => "SITI AISAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 6 bln, 4 h",
        "tgl_pengukuran" => "6/12/23",
        "berat" => "14.2",
        "tinggi" => "123",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104031608190000",
        "nama" => "KEVIN RAPSYA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "8/16/19",
        "bb_lahir" => "3.1",
        "tb_lahir" => "51",
        "nama_ortu" => "KASMAWATI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 7 bln, 7 h",
        "tgl_pengukuran" => "5/13/23",
        "berat" => "13.2",
        "tinggi" => "132",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106506810215260",
        "nama" => "KHAFITATUR RADHYYAH",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "10/28/21",
        "bb_lahir" => "3.2",
        "tb_lahir" => "49",
        "nama_ortu" => "NURJANAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 2 bln, 14 h",
        "tgl_pengukuran" => "8/12/23",
        "berat" => "15.4",
        "tinggi" => "123",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104032708899990",
        "nama" => "KHAIRUNNISAH",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "3/23/19",
        "bb_lahir" => "2.8",
        "tb_lahir" => "48",
        "nama_ortu" => "MURNI RAYATI ZIKRULLAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 6 bln, 16 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "12.2",
        "tinggi" => "102",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "110401486840001",
        "nama" => "KHALIZA SALSABILA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "10/4/22",
        "bb_lahir" => "3.1",
        "tb_lahir" => "52",
        "nama_ortu" => "HINDAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 6 bln, 16 h",
        "tgl_pengukuran" => "8/12/23",
        "berat" => "15.4",
        "tinggi" => "123",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104175211190000",
        "nama" => "KIMBELI HABIBAH AZAHRA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "12/11/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "50",
        "nama_ortu" => "DARWIN",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "2 th, 6 bln, 21 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "10",
        "tinggi" => "81",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104136203220000",
        "nama" => "LESTI AMELLIYA",
        "jenis_kelamin" => "P",
        "tgl_lahir" => "3/22/22",
        "bb_lahir" => "2.9",
        "tb_lahir" => "40",
        "nama_ortu" => "SITI AISAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 0 bln, 22 h",
        "tgl_pengukuran" => "5/13/23",
        "berat" => "9.4",
        "tinggi" => "92",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030811190000",
        "nama" => "M ALFAQIH BATUBARA",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "11/8/19",
        "bb_lahir" => "2.8",
        "tb_lahir" => "49",
        "nama_ortu" => "KASMAWATI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 7 bln, 15 h",
        "tgl_pengukuran" => "8/12/23",
        "berat" => "11",
        "tinggi" => "90",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "1",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104032401200000",
        "nama" => "M ASATAFUL QIRAM",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "1/26/20",
        "bb_lahir" => "3",
        "tb_lahir" => "48",
        "nama_ortu" => "HAJIRWAN",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 3 bln, 24 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "15.5",
        "tinggi" => "112",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1106502003225330",
        "nama" => "M GIBRAN ALFARIZKI",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "1/26/20",
        "bb_lahir" => "3",
        "tb_lahir" => "50",
        "nama_ortu" => "IKA ARMALA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 7 bln, 11 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "13",
        "tinggi" => "103",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030404190000",
        "nama" => "M NAUVAL",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "4/4/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "49",
        "nama_ortu" => "BASRAH",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 0 bln, 13 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "13.3",
        "tinggi" => "101",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "11040328012000000",
        "nama" => "M SALMAN ALFARIS",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "1/28/20",
        "bb_lahir" => "1.8",
        "tb_lahir" => "45",
        "nama_ortu" => "YANTI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "1 th, 4 bln, 20 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "6.1",
        "tinggi" => "69",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030108190000",
        "nama" => "M ZAFRAN",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "8/2/19",
        "bb_lahir" => "3.2",
        "tb_lahir" => "45",
        "nama_ortu" => "HAMDANI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 5 bln, 14 h",
        "tgl_pengukuran" => "8/11/23",
        "berat" => "15.9",
        "tinggi" => "115",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "2",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104030608190000",
        "nama" => "M ZAIN ALFATIH",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "8/6/19",
        "bb_lahir" => "3.1",
        "tb_lahir" => "50",
        "nama_ortu" => "YUDI",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "4 th, 2 bln, 2 h",
        "tgl_pengukuran" => "8/14/23",
        "berat" => "16",
        "tinggi" => "120",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ],
    [
        "nik" => "1104032507199990",
        "nama" => "M ABDUL RAJIQ",
        "jenis_kelamin" => "L",
        "tgl_lahir" => "10/13/18",
        "bb_lahir" => "3.3",
        "tb_lahir" => "51",
        "nama_ortu" => "JUSILA",
        "alamat" => "KERAMAT MUFAKAT",
        "kecamatan" => "BEBESEN",
        "usia_saat_ukur" => "3 th, 1 bln, 14",
        "tgl_pengukuran" => "3/2/22",
        "berat" => "12.4",
        "tinggi" => "101",
        "status_tinggi" => "",
        "status_berat" => "",
        "status_gizi" => "3",
        "fuzzy" => ""
    ]
];

foreach ($data as $key => $value) {
    $nama = $value['nama'];
    $nik = $value['nik'];
    $jenis_kelamin = $value['jenis_kelamin'];
    $tanggal_lahir = "2023-12-11";
    $nama_orang_tua = $value['nama_ortu'];
    $kecamatan = $value['kecamatan'];
    $alamat = $value['alamat'];
    $bb_lahir = $value['bb_lahir'];
    $tb_lahir = $value['tb_lahir'];
    $usia_saat_diukur = $value['usia_saat_ukur'];
    $berat_badan = $value['berat'];
    $tinggi_badan = $value['tinggi'];
    $tanggal_pengukuran = "2023-12-11";
    $status_tinggi = 1;
    $status_berat = 1;
    $status_gizi = $value['status_gizi'];
    $fuzzy = json_encode(['data' => 1]);
    $query_insert = "INSERT INTO table_data_balita (nik,nama,jenis_kelamin,tgl_lahir,nama_ortu,bb_lahir,tb_lahir,alamat,kecamatan,usia_saat_ukur,tgl_pengukuran,tinggi,berat,status_tinggi,status_berat,status_gizi,fuzzy) VALUES ('$nik','$nama','$jenis_kelamin','$tanggal_lahir','$nama_orang_tua','$bb_lahir','$tb_lahir','$alamat','$kecamatan','$usia_saat_diukur','$tanggal_pengukuran','$tinggi_badan','$berat_badan','$status_tinggi','$status_berat','$status_gizi','$fuzzy')";
    if (mysqli_query(koneksi(), $query_insert)) {
        $response = [
            'status' => true,
            'msg' => 'Data berhasil di tambahkan'
        ];
    } else {
        $response = [
            'status' => false,
            'msg' => "Error: " . $query_insert . "<br>" . mysqli_error(koneksi()),
        ];
    }
    echo json_encode($response);
}
function replace_data()
{
}
